---
- name: Configure Firewall
  hosts: all
  become: true
  vars: 
    firewall_rules:
      - { name: 'Allow SSH', rule: 'port 22/tcp', state: 'present'}
      - { name: 'Allow HTTP', rule: 'port 80/tcp', state: 'present'}
      - { name: 'Allow HTTPS', rule: 'port 443/tcp', state: 'present'}

  tasks:
    - name: Install Firewall (Ubuntu)
      apt:
        name: ufw
        state: present
      when: ansible_distribution == "Ubuntu"
    
    - name: Enable Firewall (Ubuntu)
      service: 
        name: ufw
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Install Firewall (CentOS)
      yum: 
        name: firewalld
        state: present
      when: ansible_distribution == "CentOS"

    - name: Enable Firewall (CentOS)
      service:
        name: firewalld
        state: started
      when: ansible_distribution == "CentOS"

    - name: Configure Firewall Rules
      firewalld:
        zone: public
        service: ssh
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: Configure Firewall Rules
      ufw:
        rule: allow
        state: enabled
      when: ansible_distribution == "Ubuntu"
